kafka:
  bootstrapServers: localhost:9092
  groupId: businessTransactionAnalyzer
  inputTopic: traces
  outputTopic: businessTraces

elasticsearch:
  host: localhost
  doc: jaeger-span-2017-12-09
  port: 9200
  scheme: html

cassandra:
 host: localhost
 keyspace: traces

database: kafka
serviceName: AppFin

startTime: 1512833158
endTime: 1512933158
interval: 1

